/**
 * Driver Contract
 * Provides the means to communicate with a shared contract interface.
 */
 
 import "../types"
 
 namespace ctt
 
 service driver (16) {
    func register_device(device device) : () = 1;
    func get_device_protocols(uuid_t deviceId) : () = 2;
    func ioctl(uuid_t deviceId, uint request, uint8[] out) : (uint8[] in, oserr_t result) = 3;
    
    event device_protocol : (uuid_t deviceId, string protocolName, uint8 protocolId) = 4;
 }
