/*
 * This file is generated by gen_props.py.
 * Do not edit this file directly.
 */

#ifndef __UNICODE_PROPS_H__
#define __UNICODE_PROPS_H__

#include <stddef.h>
#include <stdint.h>

typedef enum {
    __UNICODE_PROP_WHITESPACE = 0x1,
    __UNICODE_PROP_LOWERCASE = 0x2,
    __UNICODE_PROP_UPPERCASE = 0x4,
    __UNICODE_PROP_TITLECASE = 0x8,
    __UNICODE_PROP_LETTER = 0x10,
    __UNICODE_PROP_DIGIT = 0x20,
    __UNICODE_PROP_GRAPHIC = 0x40,
    __UNICODE_PROP_PRINTABLE = __UNICODE_PROP_GRAPHIC|__UNICODE_PROP_WHITESPACE,
    __UNICODE_PROP_ISOCONTROL = 0x80,
    __UNICODE_PROP_PUNCTUATION = 0x100,
    __UNICODE_PROP_SYMBOL = 0x200,
    __UNICODE_PROP_HEXDIGIT = 0x400,
    __UNICODE_PROP_BLANK = 0x800,
    __UNICODE_PROP_ASCII = 0x1000
} __unicode_props_t;

typedef struct {
    uint32_t          code_start;
    uint32_t          code_end;
    __unicode_props_t props;
} __unicode_ctype_t;

extern const size_t g_unicodePropsCount;
extern const __unicode_ctype_t g_unicodePropsTable[];

#endif //!__UNICODE_PROPS_H__
