/*
 * This file is generated by gen_numbers.py.
 * Do not edit this file directly.
 */

#ifndef __UNICODE_DIGIT_H__
#define __UNICODE_DIGIT_H__

#include <stddef.h>
#include <stdint.h>

typedef enum {
    __DIGIT_TYPE_NONE,
    __DIGIT_TYPE_DECIMAL,
    __DIGIT_TYPE_DIGIT,
    __DIGIT_TYPE_NUMERIC
} __digit_type_t;

typedef struct {
    uint32_t       code;
    __digit_type_t type;
    int            numerator;
    int            denominator;
} __unicode_digit_t;

extern const size_t g_unicodeDigitCount;
extern const __unicode_digit_t g_unicodeDigitTable[];

#endif //!__UNICODE_DIGIT_H__
