/*
 * This file is generated by gen_cases.py.
 * Do not edit this file directly.
 */

#ifndef DS_CASE_FOLDING_H
#define DS_CASE_FOLDING_H

#include <stddef.h>
#include <stdint.h>

typedef struct {
    uint32_t code;
    uint32_t folded_code;
} case_folding_t;

extern const size_t g_lowerCaseTableSize;
extern const case_folding_t g_lowerCaseTable[];

extern const size_t g_upperCaseTableSize;
extern const case_folding_t g_upperCaseTable[];

#endif
