#ifndef CTT_INPUT_SERVICE_SERVER_H
#define CTT_INPUT_SERVICE_SERVER_H

enum {
    CTT_INPUT_TYPE_INVALID = 0,
    CTT_INPUT_TYPE_MOUSE = 1,
    CTT_INPUT_TYPE_KEYBOARD = 2,
    CTT_INPUT_TYPE_KEYPAD = 3,
    CTT_INPUT_TYPE_JOYSTICK = 4,
    CTT_INPUT_TYPE_GAMEPAD = 5
};

#endif
