/**
 * Copyright 2016, Philip Meulengracht
 *
 * This program is free software : you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation ? , either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 *
 * errno error string table
 */

const char* g_errnoStrings[] =
{
	"No Error",
	"Not super-user",
	"No such file or directory",
	"No such process",
	"Interrupted system call",
	"I/O error",
	"No such device or address",
	"Arg list too long",
	"Exec format error",
	"Bad file number",
	"No children",
	"No more processes",
 	"Not enough core",
 	"Permission denied",
 	"Bad address",
 	"Block device required",
 	"Mount device busy",
 	"File exists",
 	"Cross-device link",
 	"No such device",
 	"Not a directory",
 	"Is a directory",
 	"Invalid argument",
 	"Too many open files in system",
 	"Too many open files",
 	"Not a typewriter",
 	"Text file busy",
 	"File too large",
 	"No space left on device",
 	"Illegal seek",
 	"Read only file system",
 	"Too many links",
 	"Broken pipe",
 	"Math arg out of domain of func",
 	"Math result not representable",
 	"No message of desired type",
 	"Identifier removed",
 	"Channel number out of range",
	"Level 2 not synchronized",
	"Level 3 halted",
	"Level 3 reset",
 	"Link number out of range",
 	"Protocol driver not attached",
 	"No CSI structure available",
	"Level 2 halted",
 	"Deadlock condition",
 	"No record locks available",
 	"Invalid exchange",
 	"Invalid request descriptor",
 	"Exchange full",
 	"No anode",
 	"Invalid request code",
 	"Invalid slot",
 	"File locking deadlock error",
 	"Bad font file fmt",
 	"Device not a stream",
 	"No data (for no delay io)",
 	"Timer expired",
 	"Out of streams resources",
 	"Machine is not on the network",
 	"Package not installed",
 	"The object is remote",
 	"The link has been severed",
 	"Advertise error",
 	"Srmount error",
 	"Communication error on send",
 	"Protocol error",
 	"Multihop attempted",
 	"Inode is remote (not really error)",
 	"Cross mount point (not really error)",
 	"Trying to read unreadable message",
 	"Inappropriate file type or format",
 	"Given log. name not unique",
 	"f.d. invalid for this operation",
 	"Remote address changed",
 	"Can't access a needed shared lib",
 	"Accessing a corrupted shared lib",
 	".lib section in a.out corrupted",
 	"Attempting to link in too many libs",
 	"Attempting to exec a shared library",
 	"Function not implemented",
    "No more files",
 	"Directory not empty",
 	"File or path name too long",
 	"Too many symbolic links",
 	"Operation not supported on transport endpoint",
	"Protocol family not supported",
    "Connection reset by peer",
 	"No buffer space available",
	"Address family not supported by protocol family",
 	"Protocol wrong type for socket",
 	"Socket operation on non-socket",
 	"Protocol not available",
 	"Can't send after socket shutdown",
 	"Connection refused",
 	"Address already in use",
 	"Connection aborted",
 	"Network is unreachable",
 	"Network interface is not configured",
 	"Connection timed out",
 	"Host is down",
 	"Host is unreachable",
 	"Connection already in progress",
 	"Socket already connected",
 	"Destination address required",
 	"Message too long",
 	"Unknown protocol",
 	"Socket type not supported",
 	"Address not available",
	"Internet connection was reset",
 	"Socket is already connected",
 	"Socket is not connected",
	"",
	"",
	"",
	"",
	"",
 	"Not supported",
    "No medium (in tape drive)",
    "No such host or network path",
    "Filename exists with different case",
	"",
 	"Value too large for defined data type",
 	"Operation canceled",
 	"State not recoverable",
 	"Previous owner died",
 	"Streams pipe error",
	"Operation would block",
	"",
	""
};
