name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build clang-cc Chef package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ 'amd64', 'i386' ]

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build and install chef
        id: chef
        uses: Meulengracht/bake/.github/actions/build-install@main
        with:
          build-type: Release
          install-prefix: ${{ runner.temp }}/chef-install

      - name: Bake the Vali system packages
        working-directory: ${{ github.workspace }}
        run: |
          export PATH="${{ steps.chef.outputs.install-prefix }}/bin:${PATH}"
          bake build --cc=vali/${{ matrix.platform }} chef/vali.yaml || true

      - name: Bake the Vali sdk packages
        working-directory: ${{ github.workspace }}
        run: |
          export PATH="${{ steps.chef.outputs.install-prefix }}/bin:${PATH}"
          bake build -p vali -a ${{ matrix.platform }} chef/sdk-c.yaml || true
